import React, { useEffect, useMemo, useState } from "react";
import { listAuditLogs, listCapabilityManifests, listConfigurations, listSaas } from "@/api/saasRegistry";
import { listConnections, listObservations } from "@/api/integrations";
import { createControlResource, listControlResources, updateControlResource } from "@/api/controlResources";
import PageHeader from "@/components/PageHeader";
import { Card, CardBody, ErrorState, KpiCard } from "@/components/ui-primitives";
import { Button } from "@/components/ui/button";
import { BrainCircuit, Boxes, Coins, Database, FileText, Flag, HardDrive, RefreshCw, Rocket, Scale, ShieldCheck, Workflow, ChevronDown, Save, X } from "lucide-react";

const text = (label, key, placeholder = "") => ({ label, key, placeholder, type: "text" });
const select = (label, key, options) => ({ label, key, type: "select", options });
const number = (label, key, placeholder = "0") => ({ label, key, placeholder, type: "number" });

const definitions = {
  screens: { title: "Governança de telas", description: "Organize módulos, telas, seções, componentes e ações sem sair deste contexto.", icon: Workflow, kind: "product_module", singular: "módulo", workspace: "Trabalhar no módulo", fields: [text("Rota principal", "route", "/administration"), text("Responsável", "owner", "Equipe de plataforma"), select("Nível na hierarquia", "level", ["Módulo", "Tela", "Seção", "Componente", "Ação"]), text("Elemento pai", "parent", "Chave do módulo ou tela")], kpis: [["Módulos cadastrados", "records"], ["Ativos", "active"], ["Telas declaradas", "manifests"], ["Alterações auditadas", "audit"]], guidance: "Defina a hierarquia e publique somente depois de revisar rotas, ações e responsável." },
  commercial: { title: "Planos e produtos", description: "Defina preço, limites, módulos incluídos e situação comercial de cada plano.", icon: Boxes, kind: "plan", singular: "plano", workspace: "Trabalhar no plano", fields: [number("Preço mensal", "price"), select("Moeda", "currency", ["BRL", "USD", "EUR"]), select("Cobrança", "billingCycle", ["Mensal", "Anual", "Sob consulta"]), number("Limite de usuários", "userLimit"), text("Módulos incluídos", "modules", "Administração, IA, Relatórios")], kpis: [["Planos", "records"], ["Planos ativos", "active"], ["Produtos vinculáveis", "products"], ["Assinaturas declaradas", "subscriptions"]], guidance: "Revise limites e módulos antes de ativar. A alteração fica versionada e auditada." },
  usage: { title: "Uso e custos", description: "Registre consumo por período, unidade e produto para acompanhar tendência e custo real.", icon: Coins, kind: "usage_record", singular: "medição", workspace: "Analisar medição", fields: [text("Métrica", "metric", "tokens, storage, jobs"), text("Período", "period", "2026-09"), number("Quantidade", "quantity"), text("Unidade", "unit", "GB, chamadas, usuários"), number("Custo apurado", "cost"), select("Moeda", "currency", ["BRL", "USD", "EUR"])], kpis: [["Medições", "records"], ["Períodos ativos", "active"], ["Produtos monitorados", "products"], ["Fontes conectadas", "connections"]], guidance: "Informe a fonte e o período. Medições sem origem confirmada devem permanecer em revisão." },
  ai: { title: "Governança de IA", description: "Controle provedores, modelos, finalidade, dados permitidos, cotas e orçamento.", icon: BrainCircuit, kind: "ai_policy", singular: "política", workspace: "Revisar política de IA", fields: [text("Provedor", "provider", "OpenAI"), text("Modelo", "model", "modelo autorizado"), text("Finalidade", "purpose", "Resumo e classificação"), number("Cota mensal", "monthlyLimit"), number("Orçamento mensal", "monthlyBudget"), text("Dados permitidos", "allowedData", "Públicos, internos anonimizados")], kpis: [["Políticas", "records"], ["Políticas ativas", "active"], ["Produtos com capacidades", "manifests"], ["Eventos auditados", "audit"]], guidance: "A IA só pode operar dentro da finalidade, cota e classificação de dados aprovadas." },
  storage: { title: "Storage e arquivos", description: "Administre provedores, regiões, quotas, retenção e disponibilidade de armazenamento.", icon: HardDrive, kind: "storage_policy", singular: "política", workspace: "Administrar armazenamento", fields: [text("Provedor", "provider", "S3, R2, Azure"), text("Bucket ou container", "bucket"), text("Região", "region", "sa-east-1"), number("Quota em GB", "quotaGb"), number("Retenção em dias", "retentionDays"), select("Criptografia", "encryption", ["Gerenciada", "Chave própria", "Pendente"])], kpis: [["Políticas", "records"], ["Armazenamentos ativos", "active"], ["Produtos", "products"], ["Conexões observadas", "connections"]], guidance: "Confirme região, retenção e criptografia antes de ativar uma política." },
  releases: { title: "Versões e publicações", description: "Acompanhe versão, ambiente, revisão, publicação e possibilidade de reversão.", icon: Rocket, kind: "release", singular: "versão", workspace: "Controlar publicação", fields: [text("Versão", "releaseVersion", "v1.0.0"), select("Ambiente", "environment", ["Homologação", "Produção", "Desenvolvimento"]), text("Commit", "commit", "SHA ou referência"), text("Responsável", "owner"), text("Data de publicação", "deployedAt", "dd/mm/aaaa hh:mm"), text("Plano de reversão", "rollback", "Como voltar com segurança")], kpis: [["Versões", "records"], ["Publicadas", "active"], ["Produtos", "products"], ["Evidências", "observations"]], guidance: "Registre evidência e plano de reversão. Publicar produção continua exigindo autorização explícita." },
  security: { title: "Segurança e acessos", description: "Conduza revisões de acesso, segredos, sessões e riscos com responsável e prazo.", icon: ShieldCheck, kind: "security_review", singular: "revisão", workspace: "Resolver revisão de segurança", fields: [select("Tipo de revisão", "reviewType", ["Acessos", "Sessões", "Segredos", "MFA", "Exceção temporária"]), select("Severidade", "severity", ["Baixa", "Média", "Alta", "Crítica"]), text("Responsável", "owner"), text("Prazo", "dueDate", "dd/mm/aaaa"), text("Evidência", "evidence", "Link, ticket ou descrição")], kpis: [["Revisões", "records"], ["Em conformidade", "active"], ["Conexões", "connections"], ["Eventos auditados", "audit"]], guidance: "Uma revisão só deve ser concluída com responsável, evidência e decisão auditável." },
  privacy: { title: "Privacidade e LGPD", description: "Mapeie categorias de dados, finalidade, base legal, retenção e responsável.", icon: Scale, kind: "data_inventory", singular: "item de dados", workspace: "Revisar tratamento de dados", fields: [text("Categoria de dados", "category", "Cadastro, financeiro, saúde"), text("Finalidade", "purpose"), select("Base legal", "legalBasis", ["Consentimento", "Contrato", "Obrigação legal", "Legítimo interesse"]), number("Retenção em dias", "retentionDays"), text("Responsável", "owner"), text("Compartilhamentos", "sharing", "Destinatários e finalidade")], kpis: [["Tratamentos", "records"], ["Aprovados", "active"], ["Produtos mapeados", "products"], ["Evidências", "audit"]], guidance: "Todo tratamento precisa de finalidade, base legal, retenção e responsável identificados." },
  continuity: { title: "Continuidade e backups", description: "Controle backups, RPO, RTO, restaurações testadas e prontidão operacional.", icon: Database, kind: "backup", singular: "plano de backup", workspace: "Validar continuidade", fields: [select("Tipo", "backupType", ["Completo", "Incremental", "Snapshot"]), select("Ambiente", "environment", ["Produção", "Homologação"]), text("Último backup", "lastBackup", "dd/mm/aaaa hh:mm"), text("RPO", "rpo", "Ex.: 1 hora"), text("RTO", "rto", "Ex.: 4 horas"), text("Último teste de restauração", "restoreTest", "Data e resultado")], kpis: [["Planos", "records"], ["Validados", "active"], ["Produtos cobertos", "products"], ["Conexões disponíveis", "connections"]], guidance: "Backup sem teste de restauração não conta como continuidade validada." },
  docs: { title: "Documentação operacional", description: "Centralize manuais, contratos de API, runbooks e responsáveis por versão.", icon: FileText, kind: "document", singular: "documento", workspace: "Editar documento operacional", fields: [select("Tipo", "documentType", ["Manual", "API", "Runbook", "Política", "Arquitetura"]), text("Produto", "product"), text("Versão", "docVersion", "v1.0"), text("Endereço", "url", "https:// ou caminho interno"), text("Responsável", "owner"), text("Revisar em", "reviewAt", "dd/mm/aaaa")], kpis: [["Documentos", "records"], ["Publicados", "active"], ["Produtos", "products"], ["Versões declaradas", "manifests"]], guidance: "Mantenha versão, responsável e próxima revisão para evitar instruções obsoletas." },
  flags: { title: "Módulos e feature flags", description: "Ative recursos por ambiente e público com rollout controlado e reversível.", icon: Flag, kind: "feature_flag", singular: "flag", workspace: "Controlar feature flag", fields: [select("Ambiente", "environment", ["Produção", "Homologação", "Desenvolvimento"]), select("Estado", "enabled", ["Ativa", "Desativada"]), number("Rollout (%)", "rollout"), text("Público", "audience", "Todos, beta, cliente específico"), text("Responsável", "owner"), text("Critério de reversão", "rollback", "Sinal que exige desativar")], kpis: [["Flags", "records"], ["Ativas", "active"], ["Configurações", "configurations"], ["Produtos", "products"]], guidance: "Use rollout gradual e registre um critério claro de reversão." },
};

const emptyCore = { key: "", name: "", description: "", status: "draft" };

function Field({ field, value, onChange }) {
  const common = { id: field.key, value: value ?? "", onChange: (event) => onChange(field.key, event.target.value), className: "mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm" };
  return <label className="text-sm font-medium text-slate-700" htmlFor={field.key}>{field.label}{field.type === "select" ? <select {...common}>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input {...common} type={field.type} placeholder={field.placeholder} />}</label>;
}

function metricValue(key, data) {
  const direct = { records: data.records.length, active: data.records.filter((item) => item.status === "active").length, products: data.products.length, manifests: data.manifests.length, configurations: data.configurations.length, connections: data.connections.length, observations: data.observations.length, audit: data.audit.length };
  return key === "subscriptions" ? data.allRecords.filter((item) => item.kind === "subscription").length : (direct[key] || 0);
}

function scrollToWorkspace() {
  requestAnimationFrame(() => {
    const workspace = document.getElementById("context-workspace");
    if (typeof workspace?.scrollIntoView === "function") workspace.scrollIntoView({ behavior: "smooth", block: "start" });
  });
}

function CapabilityCenter({ kind }) {
  const definition = definitions[kind]; const Icon = definition.icon;
  const [state, setState] = useState({ loading: true, error: false, data: null });
  const [query, setQuery] = useState(""); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState(null);
  const [form, setForm] = useState({ ...emptyCore, data: {} }); const [message, setMessage] = useState("");

  const load = async () => {
    try {
      setState((current) => ({ ...current, loading: true, error: false }));
      const [products, manifests, configurations, connections, observations, audit, records, allRecords] = await Promise.all([listSaas(), listCapabilityManifests(), listConfigurations(), listConnections(), listObservations(), listAuditLogs(), listControlResources(definition.kind), listControlResources()]);
      setState({ loading: false, error: false, data: { products, manifests, configurations, connections, observations, audit, records, allRecords } });
    } catch { setState({ loading: false, error: true, data: null }); }
  };
  useEffect(() => { load(); }, [definition.kind]);

  const records = useMemo(() => state.data?.records.filter((item) => !query || `${item.name} ${item.key} ${item.description}`.toLowerCase().includes(query.toLowerCase())) || [], [state.data, query]);
  const setData = (key, value) => setForm((current) => ({ ...current, data: { ...current.data, [key]: value } }));
  const openRecord = (record) => { setSelected(record); setCreating(false); setForm({ key: record.key, name: record.name, description: record.description, status: record.status, data: { ...record.data } }); setMessage(""); scrollToWorkspace(); };
  const openCreate = () => { const initialData = Object.fromEntries(definition.fields.filter((field) => field.type === "select").map((field) => [field.key, field.options[0]])); setSelected(null); setForm({ ...emptyCore, data: initialData }); setCreating(true); setMessage(""); scrollToWorkspace(); };
  const save = async (event) => { event.preventDefault(); const payload = { name: form.name, description: form.description, status: form.status, data: form.data }; if (selected) { const updated = await updateControlResource(selected.id, payload); setSelected(updated); setMessage("Alterações salvas e auditadas."); } else { await createControlResource({ ...payload, key: form.key, kind: definition.kind }); setCreating(false); setMessage("Registro criado e auditado."); } await load(); };

  if (state.loading) return <div className="h-64 animate-pulse rounded-xl bg-slate-100" />;
  if (state.error) return <Card><ErrorState onRetry={load} /></Card>;
  const data = state.data;
  return <div>
    <PageHeader title={definition.title} description={definition.description} icon={Icon} actions={<div className="flex gap-2"><Button variant="outline" size="sm" onClick={load}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button><Button size="sm" onClick={openCreate}>Novo {definition.singular}</Button></div>} />
    <div className="mb-5 grid grid-cols-2 gap-4 lg:grid-cols-4">{definition.kpis.map(([label, source], index) => <KpiCard key={label} label={label} value={metricValue(source, data)} icon={[Icon, ShieldCheck, Boxes, Database][index]} tone={["indigo", "emerald", "amber", "indigo"][index]} />)}</div>
    <Card className="mb-5 border-indigo-100 bg-indigo-50/40"><CardBody className="flex items-start gap-3"><Icon className="mt-0.5 h-5 w-5 text-indigo-600" /><div><p className="font-semibold text-slate-900">Como usar esta área</p><p className="text-sm text-slate-600">{definition.guidance} Clique em um registro para abrir o trabalho logo abaixo, sem sair da página.</p></div></CardBody></Card>
    <div className="mb-4 flex items-center gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Buscar ${definition.singular}...`} className="h-9 min-w-72 rounded-lg border border-slate-200 px-3 text-sm" /><span className="text-xs text-slate-500">{records.length} resultado(s)</span></div>
    {records.length === 0 ? <Card className="mb-5"><CardBody className="py-10 text-center"><p className="font-medium">Nenhum {definition.singular} cadastrado</p><p className="mt-1 text-sm text-slate-500">Crie o primeiro registro para começar a operar esta área.</p><Button className="mt-4" size="sm" onClick={openCreate}>Criar agora</Button></CardBody></Card> : <div className="mb-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{records.map((record) => <Card key={record.id} className={selected?.id === record.id ? "border-indigo-400 ring-2 ring-indigo-100" : ""}><CardBody><div className="flex justify-between gap-3"><div><p className="font-semibold">{record.name}</p><p className="text-xs text-slate-500">{record.key} · versão {record.version}</p></div><span className="h-fit rounded-full bg-indigo-50 px-2 py-1 text-xs text-indigo-700">{record.status}</span></div><p className="mt-2 min-h-10 text-sm text-slate-600">{record.description || "Sem descrição"}</p><div className="mt-3 flex flex-wrap gap-1">{definition.fields.slice(0, 3).map((field) => record.data?.[field.key] ? <span key={field.key} className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">{field.label}: {record.data[field.key]}</span> : null)}</div><Button className="mt-4 w-full" variant="outline" size="sm" onClick={() => openRecord(record)} aria-label={`Abrir ${record.name}`}>Abrir e resolver aqui <ChevronDown className="ml-2 h-4 w-4" /></Button></CardBody></Card>)}</div>}
    {(creating || selected) && <Card id="context-workspace" className="scroll-mt-6 border-indigo-300 shadow-lg"><CardBody><div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Área de trabalho contextual</p><h2 className="text-xl font-semibold text-slate-900">{definition.workspace}</h2><p className="text-sm text-slate-500">Edite, revise o estado e salve sem abandonar esta tela.</p></div><Button variant="ghost" size="icon" aria-label="Fechar área de trabalho" onClick={() => { setSelected(null); setCreating(false); }}><X /></Button></div>
      <form onSubmit={save} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {!selected && <label className="text-sm font-medium text-slate-700" htmlFor="resource-key">Chave técnica<input id="resource-key" required pattern="[a-z0-9][-a-z0-9_.]+" value={form.key} onChange={(event) => setForm({ ...form, key: event.target.value.toLowerCase() })} className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 text-sm" placeholder="exemplo.chave" /></label>}
        <label className="text-sm font-medium text-slate-700" htmlFor="resource-name">Nome<input id="resource-name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-1 h-9 w-full rounded-lg border border-slate-200 px-3 text-sm" /></label>
        <label className="text-sm font-medium text-slate-700" htmlFor="resource-status">Situação<select id="resource-status" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="draft">Rascunho</option><option value="review">Em revisão</option><option value="active">Ativo</option><option value="paused">Pausado</option><option value="archived">Arquivado</option></select></label>
        {definition.fields.map((field) => <Field key={field.key} field={field} value={form.data[field.key]} onChange={setData} />)}
        <label className="text-sm font-medium text-slate-700 md:col-span-2 xl:col-span-3" htmlFor="resource-description">Descrição e observações<textarea id="resource-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" rows={3} /></label>
        <div className="flex items-center gap-2 md:col-span-2 xl:col-span-3"><Button type="submit"><Save className="mr-2 h-4 w-4" />{selected ? "Salvar alterações" : "Criar registro"}</Button><Button type="button" variant="outline" onClick={() => { setSelected(null); setCreating(false); }}>Cancelar</Button>{message && <span role="status" className="text-sm font-medium text-emerald-700">{message}</span>}</div>
      </form></CardBody></Card>}
  </div>;
}

export const ScreenGovernance = () => <CapabilityCenter kind="screens" />;
export const CommercialCenter = () => <CapabilityCenter kind="commercial" />;
export const UsageCostCenter = () => <CapabilityCenter kind="usage" />;
export const AiGovernance = () => <CapabilityCenter kind="ai" />;
export const StorageCenter = () => <CapabilityCenter kind="storage" />;
export const ReleaseCenter = () => <CapabilityCenter kind="releases" />;
export const SecurityCenter = () => <CapabilityCenter kind="security" />;
export const PrivacyCenter = () => <CapabilityCenter kind="privacy" />;
export const ContinuityCenter = () => <CapabilityCenter kind="continuity" />;
export const DocumentationCenter = () => <CapabilityCenter kind="docs" />;
export const FeatureCenter = () => <CapabilityCenter kind="flags" />;
